### ISSUE TITLE
Render geospacial objects on a map

### ISSUE THREAD

**Issue by elecnix** [MasseGuillaume/ScalaKata2#14]
I think #13 could lead to supporting the rendering of points, polygons, and other geospacial types on a map.

This would enable one to play with a geospacial API such as GeoScript (https://github.com/dwins/geoscript.scala) and actually see the result.

**Comment by MasseGuillaume** [comment]
https://github.com/MasseGuillaume/ScalaKata2/issues/13#issuecomment-181172953
