### ISSUE TITLE
Result values are misaligned

### ISSUE THREAD

**Issue by raboof** [MasseGuillaume/ScalaKata2#18]
![selection_056](https://cloud.githubusercontent.com/assets/131856/12268950/5309e50a-b94f-11e5-8b82-f78c446a24c9.png)

Looks like the location of result values are specified relative to the right boundary of the expression. I'm not sure how the distance is determined, but they don't line up.

(might be a issue with CodeMirror, but let's start tracking here)

**Comment by MasseGuillaume** [comment]
I remember having this issue

I can't reproduce with master. I guess it's related to https://github.com/MasseGuillaume/ScalaKata2/commit/a3821471d655b97e77cb13ccd7479f39b0e10127#diff-074ab1bd2615846d631b39270a11bedcL98

**Comment by raboof** [comment]
(how) can I see which version is running on scalakata.com ? It's definitely still there.

**Comment by MasseGuillaume** [comment]
I did not yet update scalakata.com

https://github.com/MasseGuillaume/ScalaKata2/issues/22
