### ISSUE TITLE
Unable to build the project using SBT

### ISSUE THREAD

**Issue by kingspp** [MasseGuillaume/ScalaKata2#21]
**Environment:**

SBT: 0.13.9
Scala: 2.11.7
IDE: IntelliJ 15

I have added scalakata in plugins.sbt and enabled in build.sbt

Error:

**EvalSetup.scala**

``` scala
  private val artifacts = BuildInfo.runtime_fullClasspath.map(v ⇒ Paths.get(v.toURI))
  private val scalacOptions = build.BuildInfo.scalacOptions.to[Seq]
```

cannot resolve BuildInfo

**MacroSpecs.scala**

``` scala
withOffset(new VarVal) ====  List(
      RangePosition( 8,  8, 13) -> Other("2"),
      RangePosition(22, 22, 27) -> Other("4")
    )
  }


withOffset(new Full) ==== List(
      RangePosition(  8,   8,  13) -> EString("L29"),
      RangePosition( 22,  22,  27) -> EString("L30"),
      RangePosition( 28,  28,  33) -> EString("L29L30"),
      RangePosition( 42,  42,  47) -> EString("L29L30"),
      RangePosition( 49,  49,  56) ->   Other("Set(33)"),
      RangePosition(151, 151, 160) -> EString("L34v"),
   ...
    )
```

Error:(25, 16) type mismatch;
 found   : VarVal
 required: com.scalakata.Instrumented
    withOffset(new VarVal) ====  List(
               ^

Can you let me know the proper way to build it?

**Comment by MasseGuillaume** [comment]
Those errors are related to intellij. If you build with sbt from the command line it should work.

**Comment by kingspp** [comment]
Thank you for your reply, However I was able to clean compile the project. I am a newbie to scala and sbt. Can you please let me know how to start the server?

**Commands tried:**

```
sbt run 
sbt run webappJVM
sbt "run-main com.scalakata.Boot"
```

**Error:**

```
 No main class detected
Class not found exception
```

**Comment by MasseGuillaume** [comment]
If you want to develop ScalaKata, you can use `sbt ~webappJVM/reStart`.

If you want to use ScalaKata. You can use
- [an hosted instance](http://scalakata.com)
- [a docker container](https://github.com/MasseGuillaume/ScalaKata2#docker-containers)
- [a sbt plugin](https://github.com/MasseGuillaume/ScalaKata2/tree/master/dockerContainer)
  - start with `sbt` then `kstart`
