### ISSUE TITLE
collaborative coding

### ISSUE THREAD

**Issue by MasseGuillaume** [MasseGuillaume/ScalaKata2#24]
a la google doc !

**Comment by nafg** [comment]
isn't sharing snippets a prerequisite?

**Comment by MasseGuillaume** [comment]
more or less. sharing snippets would imply some persistence. Dont worry, I will do saving soon :P

**Comment by MasseGuillaume** [comment]
now live at http://scalakata.com

**Comment by nafg** [comment]
How does it work?

**Comment by MasseGuillaume** [comment]
It's silently deployed :P

visit `http://scalakata.com/room/<some-name>`

like: http://scalakata.com/room/nafg
