### ISSUE TITLE
errors are not aligned

### ISSUE THREAD

**Issue by raboof** [MasseGuillaume/ScalaKata2#28]
scalac errors sometimes 'point' at the character containing the error, but show up in scalakata at the first column of the statement:
![selection_069](https://cloud.githubusercontent.com/assets/131856/13724040/b7c91e4a-e878-11e5-92b0-7911fe806496.png)

**Comment by MasseGuillaume** [comment]
Thanks, I will take a look at this one soon.

**Comment by raboof** [comment]
That'd be fantastic - great work btw, I feel kinda bad about just complaining about stuff in the issues instead of contributing any code so far :)

**Comment by MasseGuillaume** [comment]
Don't worry I prefer to have issues open than no issues at all ;-).

**Comment by MasseGuillaume** [comment]
2a26e55d06506a70b4fcb25ae3e2ec596ff3355f

**Comment by MasseGuillaume** [comment]
now live at http://scalakata.com
