### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by alexbrand** [MasseGuillaume/ScalaKata2#29]
ScalaKata is awesome! Have you thought of having a donate button or something? So that you can get help with the hosting cost.

Cheers

**Comment by MasseGuillaume** [comment]
Glad you like it. The hosting cost is currently covered by [Lightbend](http://www.lightbend.com/). I will eventually merge this project into [scala-exercices](http://scala-exercises.47deg.com).

For the donate button, [I prefer not to have one](http://www.angelfire.com/md2/timewarp/rousseau.html).
