### ISSUE TITLE
macro annotation could not be expanded

### ISSUE THREAD

**Issue by raboof** [MasseGuillaume/ScalaKata2#34]
when I open scalakata.com, I get `macro annotation could not be expanded (the most common reason for that is that you need to enable the macro paradise plugin; another possibility is that you try to use macro annotation in the same compilation run that defines it)` under `@instrument`

**Comment by MasseGuillaume** [comment]
Aw the compiler crashed

**Comment by MasseGuillaume** [comment]
Ok, it's back on. I will put something to automatically restart the compiler when it crashes.

**Comment by raboof** [comment]
Is it down again?

**Comment by MasseGuillaume** [comment]
restarted

**Comment by raboof** [comment]
I'm afraid it's down again?

**Comment by MasseGuillaume** [comment]
@raboof Hey I'm really sorry I'm at Scala Days and had less time to restart the server. I really have to find a more permanent solution to this problem. Stay tuned !

**Comment by raboof** [comment]
No problem have fun!

**Comment by raboof** [comment]
(plus responding within 3 hours is basically super fast in any case ;) - thanks!)

**Comment by MasseGuillaume** [comment]
fix in 71ee9f3a16d9b6008e5f5116ee5b046d4936e143
