### ISSUE TITLE
Pressing "?" button loses any changes done so far

### ISSUE THREAD

**Issue by pietro909** [MasseGuillaume/ScalaKata2#42]
Hi,
yesterday I did some exercise from a book and suddenly **I lost them** because I was looking for the help... I think that the editor should cache it temporarily so that at least can avoid losing all the code written so far.

However, amazing real-time completion!

**Comment by MasseGuillaume** [comment]
I'm really sorry about that. If you still have the tab open you can undo with `ctrl+z`.

**Comment by pietro909** [comment]
I already closed the tab, but you know what? I opened it now to test the `ctrl+z` trick and... my code was there!

I should have tried harder, sorry! Closing as it's not an issue 👍
