### ISSUE TITLE
Please state the version of scalac you're using somewhere

### ISSUE THREAD

**Issue by makoConstruct** [MasseGuillaume/ScalaKata2#5]
ScalaKata could be quite useful for confirming bugs on the most recent version of the compiler (which I rarely have at hand on my own machine) before reporting them.

**Comment by MasseGuillaume** [comment]
If this issue is about scalakata.com, I provide this information indirectly in the help info

> [A lot of dependencies are included](https://github.com/MasseGuillaume/ScalaKata2/blob/master/dockerContainerBundle/built.sbt#L1) with scalakata.

**Comment by MasseGuillaume** [comment]
I added the version in the `help` command
